[package]
name = "monkey-lang"
version = "0.1.0"
edition = "2021"

[lib]
name = "monkey_lang"
path = "src/lib.rs"

[[bin]]
name = "monkey"
path = "src/main.rs"

[dependencies]
colored = "3.0.0"
users = "0.11.0"
