[package]
name = "monkey-lang"
version = "0.1.0"
edition = "2021"

[lib]
name = "monkey_lang"
path = "cli/lib.rs"

[[bin]]
name = "monkey"
path = "cli/main.rs"

[dependencies]
colored = "3.0.0"
users = "0.11.0"
log = "0.4.28"
env_logger = "0.11.8"

